wastingtimer/nprofile/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from views import ProfileView, WastageView


urlpatterns = patterns('',
    url(r'^(?P<slug>.+)/profile/$', login_required(ProfileView.as_view()), name="profile"),
    url(r'^(?P<slug>.+)/wastage/$', login_required(WastageView.as_view()), name="wastage"),
    url(r'^dashboard/$', TemplateView.as_view(template_name='nprofile/dashboard.html'), name="dashboard"),
)

wastingtimer/theme/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView


urlpatterns = patterns('',
    url(r'^about-us/$', TemplateView.as_view(template_name='theme/about_us.html'), name="about_us"),
    url(r'^(?P<slug>.+)/profile/$', login_required(TemplateView.as_view(template_name='theme/profile.html')), name="profile"),
    url(r'^$', TemplateView.as_view(template_name='theme/index.html'), name="index"),
)

wastingtimer/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),
    url(r'^auth/', include('social_auth.urls')),
    url(r'^wasters/', include('wastingtimer.wasters.urls', namespace='wasters')),
	url(r'^', include('wastingtimer.wasted.urls', namespace='wasted')),
    url(r'^', include('wastingtimer.nprofile.urls', namespace='nprofile')),
    url(r'^', include('wastingtimer.theme.urls', namespace='theme')),
)

wastingtimer/wasted/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from views import UserEditView


urlpatterns = patterns('',
    url(r'^latest/$', TemplateView.as_view(template_name='wasted/latest_list.html'), name="latest"),
    url(r'^(?P<pk>.+)/edit/$', login_required(UserEditView.as_view()), name="edit"),
)

wastingtimer/theme/models.py
from django.db import models

# Create your models here.
from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField()
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)

wastingtimer/theme/views.py
# Create your views here.
from django.shortcuts import render
from django.http import HttpResponseRedirect

def about_us(request):
    if request.method == 'POST': # If the form has been submitted...
        form = ContactForm(request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            sender = form.cleaned_data['sender']

            recipients = ['tim@buchwaldt.ws']

            from django.core.mail import send_mail
            send_mail(subject, message, sender, recipients)
            return HttpResponseRedirect('about-us/thanks/')
    else:
        print "seems like a get request"
        form = ContactForm() # An unbound form

    return render(request, 'contact.html', {
        'form': form,
    })

wastingtimer/theme/templates/theme/about_us.html
{% extends 'base.html' %}

{% block body %}
<h1>Hey, we are Ross &amp; Tim</h1>
<p>
    two developers based in Cologne, Germany.<br/>
    Frustrated by the german public transport and generally wasting time waiting, we built minuteswastedapp.com during our spare time.<br/>
  You will soon be able to contact us via a form that will be here.. somewhere.
</p>

<hr/>

<div class="span5">
<h2>Ross Crawford-d'Heureuse<br/><small>The #startup_life</small></h2>
<p>Anyone who has ever run a startup knows: <b>Its really difficult</b>.</p><p>Not just the work and the pressures thereof, but also managing your home-life.</p>
<p>With this in mind I entered into an agreement with my wife stating that I would record all the of excess minutes that I spend on my startup (http://lawpal.com). By using @minutes_wasted I am able to quickly and easily record that time, as well as time spend on other tasks in the #startup_life.</p>
</div>

<div class="span5">
<h2>Tim Buchwaldt</h2>
<p>I'm always busy doing something - be it reading the news about devops and systems architecture, keeping some server up and stable or programming just for fun. As I'm located in the beautiful city of Sinzig, I have to commute to and from Cologne, which takes enormous amounts of my time due to some trains being notoriously late.  </p>
</div>

<hr/>

{% endblock %}

wastingtimer/theme/templates/theme/index.html
{% extends 'base.html' %}
{% load wasted_tags cache %}

{% load url from future %}

{% block body %}
<div class="row-fluid demo-headline">
  <h1 class="demo-logo">
    <em style="color:#16A085;">n</em> Minutes wasted
    <small style="color:#BDC3C7">Keeping track of <em>all</em> your time.</small>
  </h1>
    <div id="example_wrapp">
      <ul id="examples" class="unstyled">
        <li>Late public transport</li>
        <li>Waiting to see a doctor/dentist/vet/lawyer</li>
        <li>Waiting on plumber/telephone technician</li>
        <li>Being on hold in a call</li>
        <li>Traffic jams</li>
        <li>Timesheets</li>
        <li>Fast food delivery</li>
        <li>Resturants waiting on your order</li>
        <li>Waiting for people to show up at meetings</li>
        <li>Waiting on colleagues</li>
        <li>Installing software</li>
        <li>Waiting on SLA notices</li>
      </ul>
    </div>
</div> <!-- /demo-headline -->

<div class="hero-unit">
      <h2>Don't login!</h2>
      <p>Just start sending tweets in the format shown in the example below.</p>

      <h2>How do I record my time</h2>
      <p>Simply send a tweet like:
        <br/>
        <code>@minutes_wasted 0:15 #traffic_jam On my way to work! Need more coffee</code>
      </p>
      <p>We record this tweet, and create the #traffic_jam category for future use, as well as store the message for your records.</p>
      <p>You can then keep a record of all the time that you "<i>waste</i>"!</p>
      <p>&nbsp;</p>

      <h2>But I dont want the world to know what I'm spending my time on?</h2>
      <p>No problem, simply send a tweet like the example above introducing yourself to @minutes_wasted (who will then follow you), and then you can follow @minutes_wasted which lets you <strong><em>direct message</em></strong> your private records.</p>
      <p>&nbsp;</p>

      <h2>Whats it look like?</h2>
      <p>It is a bit basic at the moment, but we are open to suggestion.</p>
      <p><img src="{{ STATIC_URL }}images/dash-basic.png" alt="Basic Overview" title="Basic Overview"/></p>
  
</div>

<div class="row-fluid">

      <h2>Latest</h2>
      {% cache 30 wasted.latest.front_page %}
        {% latest_tweets max=6 %}
      {% endcache %}

</div>
{% endblock %}

wastingtimer/theme/templates/theme/nav.html
<ul class="nav">
  <li>
    <a href="/">
      <em style="color:#16A085;">n</em> Minutes wasted
    </a>
  </li>
  <li>
    <a href="{% url 'theme:about_us' %}">
      About Us
    </a>
  </li>
  <li>
    <a href="{% url 'wasted:latest' %}">
      Latest
    </a>
  </li>
  <li>
    <a href="{% url 'wasters:index' %}">
      Wasters
    </a>
  </li>
  {% if not user.is_authenticated %}
  <li>
    <a href="{% url 'socialauth_begin' backend='twitter' %}">
      Login via Twitter
    </a>
  </li>
  {% else %}
  <li>
    <a href="{% url 'theme:profile' slug=user.username %}">
      Dashboard ({{ user.username }})
    </a>
    <ul>
        <li><a href="{% url 'nprofile:wastage' slug=user.username %}">Your Wastage</a></li>
        <!--<li><a href="#">Your Categories</a></li>-->
        <li><a href="{% url 'logout' %}">Logout</a></li>
    </ul>
  </li>
  {% endif %}
</ul>