wastingtimer/theme/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView


urlpatterns = patterns('',
    url(r'^about-us/$', TemplateView.as_view(template_name='theme/about_us.html'), name="about_us"),
    url(r'^(?P<slug>.+)/profile/$', login_required(TemplateView.as_view(template_name='theme/profile.html')), name="profile"),
    url(r'^$', TemplateView.as_view(template_name='theme/index.html'), name="index"),
)

wastingtimer/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),
    url(r'^auth/', include('social_auth.urls')),
    url(r'^wasters/', include('wastingtimer.wasters.urls', namespace='wasters')),
	url(r'^', include('wastingtimer.wasted.urls', namespace='wasted')),
    url(r'^', include('wastingtimer.nprofile.urls', namespace='nprofile')),
    url(r'^', include('wastingtimer.theme.urls', namespace='theme')),
)

wastingtimer/wasted/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from views import UserEditView


urlpatterns = patterns('',
    url(r'^latest/$', TemplateView.as_view(template_name='wasted/latest_list.html'), name="latest"),
    url(r'^(?P<pk>.+)/edit/$', login_required(UserEditView.as_view()), name="edit"),
)

wastingtimer/wasted/models.py
# -*- coding: UTF-8 -*-
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.encoding import smart_unicode

from taggit.managers import TaggableManager
from jsonfield import JSONField

from wastingtimer.utils import TWEET_TYPES, get_namedtuple_choices
from managers import WastedManager, WastedPublicManager, WastedPrivateManager, WastedUserManager

import re

User = get_user_model()


class Wasted(models.Model):
    """ Model for wasted time tweets 
    stores the tweets
    """
    user = models.ForeignKey(User)
    timedelta_total_secs = models.FloatField(null=True,)
    tweet = models.CharField(max_length=255, null=True)
    twitter_id = models.BigIntegerField(db_index=True)
    tweet_type = models.IntegerField(choices=TWEET_TYPES.get_choices(), db_index=True)
    tweet_data = JSONField(default={})
    created_at = models.DateTimeField(auto_now=False, auto_now_add=False, db_index=True)

    tags = TaggableManager()

    objects = WastedManager()
    public = WastedPublicManager()
    private = WastedPrivateManager()
    user_objects = WastedUserManager()

    def __unicode__(self):
        return u'%s - %s' % (self.text, self.created_at,)

    @property
    def is_private(self):
        """ Direct Messages are regarded as
        private tweets
        """
        return self.tweet_type == TWEET_TYPES.dm

    @property
    def text(self):
        """ Extract the tweet.text from the saved tweet json object 
        store as property for easy reference
        """
        text = self.tweet if self.tweet else self.tweet_data.get('text', None)
        if text:
            text = re.sub(r'\@minutes_wasted', '',text)
        return u'%s' % smart_unicode(text if text else u'No Tweet Text Found')

    @property
    def geo(self):
        return self.tweet_data.get('geo', None)

    @property
    def source(self):
        return self.tweet_data.get('source', None)

    @property
    def hashtags(self):
        """ Extract the inbuilt twitter hashtag for use as categories 
        """
        tags = []
        try:
            tags = [t.name for t in self.tags.all()]
            tags[0]
        except:
            if self.tweet_data and 'entities' in self.tweet_data:
                tags = [unicode(i['text']).lower() for i in self.tweet_data['entities'].get('hashtags', [])]
        return tags

    def extract_hashtags(self,text=None):
        text = text if text is not None else self.text
        return re.findall(r'(#\w+)', text)

    def extract_time(self):
        """ Extract the proposed wasted time 
        27min 2hrs etc.. try to make it as inclusive as possible
        datetime libs
        """
        hours,minutes = 0,0
        find = re.search(ur"(\d+:\d+)", self.text, re.UNICODE)
        if find:
            hours,minutes = find.group(0).split(":")
        return (int(hours)*60) + int(minutes)


class TwitterSince(models.Model):
    """ Model for saving the since_id of the
    last imported tweet """
    since_id = models.BigIntegerField()
    since_type = models.IntegerField(choices=TWEET_TYPES.get_choices(), unique=True, db_index=True)

# Must be defined in models.py and at the end of the file so it auto loads
from signals import extract_tags

wastingtimer/wasted/forms.py
from django import forms
from django.utils.translation import ugettext as _

from parsley.decorators import parsleyfy
from models import Wasted


@parsleyfy
class UserWastedForm(forms.Form):
    tweet = forms.CharField(label=_('Tweet'), help_text='', required=True, min_length=20, max_length=140, widget=forms.Textarea(attrs={'class':'xxlarge'}))

    def __init__(self, **kwargs):
        self.request = kwargs.pop('request', None)
        self.object = kwargs.pop('object', None)
        super(UserWastedForm, self).__init__(**kwargs)

    def save(self):
        if self.object:
            tweet = self.cleaned_data.get('tweet')
            tags = self.object.extract_hashtags(text=tweet)
            # set the main text object and not the tweet.data
            self.object.tweet = tweet
            self.object.save()
            # handle tags
            self.object.tags.all().delete()
            self.object.tags.add(*tags)

        return self.object
        

wastingtimer/wasted/views.py
from django.utils.translation import ugettext as _
from django.views.generic import DetailView
from django.views.generic.edit import FormMixin
from django.views.generic.detail import SingleObjectMixin
from django.core.urlresolvers import reverse
from django.contrib import messages
from models import Wasted
from forms import UserWastedForm


class UserEditView(DetailView, SingleObjectMixin, FormMixin):
    form_class = UserWastedForm
    model = Wasted
    template_name = 'wasted/wasted_form.html'

    def get_success_url(self):
        return reverse('wasted:edit', kwargs={'pk': self.object.pk})

    def get_form(self, form_class):
        data = self.get_form_kwargs()

        # inject initial if we have it
        if hasattr(self, 'object'):
            data['initial'].update({
                'tweet': self.object.text,
            })

        # inject these values into the form, so we can access
        # the request and user objects
        data.update({
            'request': self.request,
            'object': getattr(self, 'object', None),
        })

        return form_class(**data)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object() # this is the key element here
        form_class = self.get_form_class()
        form = self.get_form(form_class)

        if form.is_valid():
            form.save() # manually call save as its not a model form
            messages.success(request, _('Successfully, updated this wasted message.'))
            return self.form_valid(form)
        else:
            messages.warning(request, _('Oh dear, it looks like there was a problem.'))
            return self.form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super(UserEditView, self).get_context_data(**kwargs)
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        context.update({
            'form': form,
        })
        context.update(kwargs)
        return context

wastingtimer/wasted/templates/wasted/latest.html
{% load humanize %}
{% for w in object_list %}
<div class="waste span5">
  <h6>{{ w.extract_time }}min by</h6>
  
    <div class="span2">
      <!-- <span class="create_at">{{ w.created_at|naturaltime }}</span>-->
    	<a href="{% url 'nprofile:profile' slug=w.user.username %}"><img src="{{ w.user.get_profile.twitter_image }}" title="{{ w.user.username }}" class="user_image small" border="0"/></a>
    	<a href="{% url 'nprofile:profile' slug=w.user.username %}">{{ w.user.username }}</a>
    </div>
    <div class="span9">{{ w.text }}</div>
  
</div>
{% empty %}
<div class="waste">
  None Found
</div>
{% endfor %}

wastingtimer/wasted/templates/wasted/latest_list.html
{% extends 'base.html' %}
{% load wasted_tags cache %}
{% load url from future %}

{% block body %}
<div class="row-fluid">
	<h2>Latest wastes</h2>
	{% cache 30 wasted.latest.main_list %}
		{% latest_tweets max=50 %}
	{% endcache %}
</div>
{% endblock %}

wastingtimer/wasted/templates/wasted/wasted_form.html
{% extends 'base.html' %}{% load wasted_tags cache crispy_forms_tags humanize i18n %}
{% load url from future %}

{% block body %}
<div class="hero-unit">
    <div class=""><b>Created:</b>&nbsp;<small>{{ object.created_at|naturaltime }} ({{ object.created_at }})</small></div>
    <div class=""><b>Source:</b>&nbsp;<small>{{ object.source }}</small></div>
    {% if object.geo %}<div class=""><b>Geo:</b>&nbsp;<small>{{ object.geo }}</small></div>{% endif %}
    <div class=""><b>Categories:</b>&nbsp;<ul id="tag_list" class="unstyled"></ul></div>
</div>
<div class="row-fluid">
    <form id="edit-tweet" data-validate="parsley" action="{% url 'wasted:edit' pk=object.pk %}" method="POST">{% csrf_token %}
        {{ form|crispy }}
        <div class="control-group">
            <div class="controls">
                <button type="submit" class="btn">{% trans 'Update' %}</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

{% block css %}
<style>
form textarea{
    height:90px;
}
</style>
{% endblock %}

{% block js %}
<script>
$(document).ready(function(){
    var tags = {{ object.hashtags|as_json_string }};
    $('#id_tweet').addClass('span7')
    $.each(tags, function(i,item){
        $('#tag_list').append($('<li/>',{
            class: 'span'
            ,html: '<small><em>'+item+'</em></small>'
        }))
    })
});
</script>
{% endblock %}

wastingtimer/wasted/templates/wasted/wasted_list.html
{% extends 'base.html' %}
{% load humanize %}

{% block body %}
  <div class="row-fluid">
    <h2>All your wastes</h2>
    {% for w in object_list %}
      <div class="waste span5">
        {% if w.user == user %}<div class="pull-right"><a href="{% url 'wasted:edit' pk=w.pk %}">Edit</a></div>{% endif %}
        <div class="span2">
            <h6>{{ w.extract_time }}min</h6>
            <a href="{% url 'nprofile:profile' slug=w.user.username %}"><img src="{{ w.user.get_profile.image_or_placeholder }}" title="{{ w.user.username }}" class="user_image small" border="0"/></a>
            <a href="{% url 'nprofile:profile' slug=w.user.username %}">{{ w.user.username }}</a>
        </div>
        <div class="span9">{{ w.text }}</div>
        <br/>
        <div class="pull-right"><small>{{ w.created_at|naturaltime }}</small></div>
      </div>
    {% empty %}
      <div class="waste">
        None Found
      </div>
    {% endfor %}
  </div>
{% endblock %}